# Generated by Django 4.2.9 on 2024-02-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile/profile_picture.jpeg', upload_to='profile_pictrues/'),
        ),
    ]
