# Generated by Django 4.2.9 on 2024-02-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlowApp', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictrues/'),
        ),
    ]
