# Generated by Django 4.2.9 on 2024-02-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlowApp', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media_files/'),
        ),
    ]
