# Generated by Django 4.2.9 on 2024-02-16 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GlowApp', '0007_media_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_likescount',
        ),
        migrations.AddField(
            model_name='media',
            name='media_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
