# Generated by Django 4.2.9 on 2024-02-17 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlowApp', '0008_remove_media_media_likescount_media_media_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
